# Generated by Django 4.1.2 on 2022-10-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('adress_personal', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('identification', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
