# Generated by Django 4.1.2 on 2022-10-26 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('city', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=30)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='home_care.person')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('record', models.CharField(max_length=30)),
                ('speciality', models.CharField(max_length=30)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='home_care.person')),
            ],
        ),
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('marital_status', models.CharField(max_length=30)),
                ('grade_level', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='home_care.patient')),
                ('born_city', models.CharField(max_length=30)),
                ('patient_profile', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('blood_pressure', models.CharField(max_length=30)),
                ('respiration_rate', models.CharField(max_length=30)),
                ('pulse_rate', models.CharField(max_length=30)),
                ('id_vital_sign', models.AutoField(primary_key=True, serialize=False)),
                ('body_temperature', models.CharField(max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home_care.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='home_care.person')),
                ('roles', models.ManyToManyField(to='home_care.role')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAssigment',
            fields=[
                ('id_patient_assigment', models.AutoField(primary_key=True, serialize=False)),
                ('patient_relation', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('assigment_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home_care.person')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home_care.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HealthSuggestions',
            fields=[
                ('id_health_suggestion', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.CharField(max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home_care.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id_record', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostic', models.CharField(max_length=250)),
                ('health_history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home_care.healthhistory')),
            ],
        ),
    ]
